Repository spring-projects/spring-data-commons, pull requests merged in 2022-08, with the labels that each got.

#2672 Fix the JDK version required to build from the source code
  README.adoc
Labels: status: waiting-for-triage

#2652 Specify title to `auditing.auditor-aware`.
  src/main/asciidoc/auditing.adoc
Labels: type: documentation

#2668 Change initialCapacity to match the number of data being added.
  src/main/java/org/springframework/data/auditing/AnnotationAuditingMetadata.java
Labels: type: enhancement
